remote_theme: "mmistakes/minimal-mistakes@4.19.3"

title: "Emma Woods"
subtitle: "Data Science Portfolio"

# Plugins (previously gems:)
plugins:
- jekyll-include-cache

include: ["_pages"]

breadcrumbs: true  # disabled by default


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
